name: asunder-casept
version: '2.8.1'
summary: Asunder is a graphical Audio CD ripper and encoder for Linux.
description: |
  Asunder is a graphical Audio CD ripper and encoder for Linux.
  You can use it to save tracks from an Audio CD as any of WAV, MP3, OGG,
  FLAC, Opus, WavPack, Musepack, AAC, and Monkey's Audio files.
  This is an unofficial snap.

  
grade: stable 
confinement: strict

apps:
  asunder:
    command: desktop-launch $SNAP/bin/asunder
    # Network permission is needed in order to access CDDB
    plugs: [x11, unity7, home, optical-drive, network]
parts:
  asunder:
    plugin: autotools
    source: http://littlesvr.ca/asunder/releases/asunder-2.8.1.tar.bz2
    stage-packages:
      - cdparanoia
      - libatk1.0-0
      - libc6
      - libcddb2
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - vorbis-tools
      - flac
      - wavpack
      - lame
    build-packages:
      - build-essential
      - autotools-dev
      - libcddb2-dev
      - libgtk2.0-dev
      - intltool
    after: [desktop-gtk2]
